version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: ajv
    versions:
    - 7.1.0
    - 7.2.1
    - 7.2.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.26
    - 14.14.28
    - 14.14.32
    - 14.14.33
    - 14.14.34
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.0
    - 4.17.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.17.0
  - dependency-name: "@types/koa"
    versions:
    - 2.11.8
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.16
  - dependency-name: typescript
    versions:
    - 4.1.4
