version: "3.3"
services:
  pathfinder-core:
    image: pathfinder-core:pathfinder/core
    # container_name: pathfinder-core
    build: .
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    expose:
      - "3002"
