# This scenario builds pathfinder-core image.
version: "3.3"
services:
  core:
    image: pathfinder-core
    build: .
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    expose:
      - "3002"
