version: "3.3"
services:
  postgresql:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
  rabbitmq:
    image: "rabbitmq"
    ports:
    - "5672:5672"
    - "15672:15672"