apiVersion: v1
kind: Service
metadata:
  name: atlas-3002
  namespace: atlas
spec:
  selector:
    app: atlas-core-app-2
  ports:
    - port: 3002
      nodePort: 30022
  externalIPs:
    - 83.150.204.38
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: atlas-3003
  namespace: atlas
spec:
  selector:
    app: atlas-core-app-3
  ports:
    - port: 3003
      nodePort: 30023
  externalIPs:
    - 83.150.204.38
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: atlas-3004
  namespace: atlas
spec:
  selector:
    app: atlas-core-app-4
  ports:
    - port: 3004
      nodePort: 30024
  externalIPs:
    - 83.150.204.38
  type: NodePort
