name: Docker Image Publishing CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    # if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # install docker compose ^^^^
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@34d5f75b0d6d0d22f06d83acf2fa1b144409ec83
      uses: docker/login-action@v1.4.1
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # Username used to log against the Docker registry
        username: danilandreev
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.DOCKER_HUB_DA_TOKEN}}
        # Log out from the Docker registry at the end of a job
        logout: true
    - name: Build the Docker image
      run: docker-compose build
    - name: List of images in local docker registry
      run: docker images
    - name: Push image to docker
      run: docker push pathfnder/core:1.0.0
