name: Update Pathfinder data storage.

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE_STORAGE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_STORAGE_ZONE }}
  APPLICATION_CREDENTIALS: ${{secrets.GCE_SA_KEY}}

jobs:
  gcloud: 
    runs-on: ubuntu-latest
    name: Setup, Build, Publish, and Deploy to GCloud
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup gcloud CLI
      - name: Setup GCloud environment
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ secrets.GCE_PROJECT }}
#       - name: Restart using bash script on server
#         uses: actions-hub/gcloud@master
#         with: 
#           args: compute ssh --zone ${{ secrets.GCE_INSTANCE_ZONE }} --command='sudo bash "deploy.sh"' ${{secrets.GCE_INSTANCE}} 
#           - run: docker stop $(docker ps -a -q)
      - name: Clone git repository
        uses: actions-hub/gcloud@master
        with: 
          args: compute ssh --zone ${{ secrets.GCE_INSTANCE_ZONE }} ${{secrets.GCE_INSTANCE}} --command 'sudo git clone "https://github.com/Pathfinder-Systems/pathfinder-core.git"'
      - name: Delete old docker-compose scenario.
        uses: actions-hub/gcloud@master
        with: 
          args: compute ssh --zone ${{ secrets.GCE_INSTANCE_ZONE }} ${{secrets.GCE_INSTANCE}} --command 'sudo rm -f "docker-compose.yaml"'
      - name: Move docker-compose configuration file to the root and rename it to docker-compose.yaml
        uses: actions-hub/gcloud@master
        with: 
          args: compute ssh --zone ${{ secrets.GCE_INSTANCE_ZONE }} ${{secrets.GCE_INSTANCE}} --command 'sudo mv "pathfinder-core/docker-compose/pathfinder-data-storage-start.yaml" "docker-compose.yaml"'
      - name: Delete git repository
        uses: actions-hub/gcloud@master
        with: 
          args: compute ssh --zone ${{ secrets.GCE_INSTANCE_ZONE }} ${{secrets.GCE_INSTANCE}} --command 'sudo rm -rf "pathfinder-core"'
#       - name: Stop all containers
#         uses: actions-hub/gcloud@master
#         with: 
#           args: compute ssh --zone ${{ secrets.GCE_INSTANCE_ZONE }} ${{secrets.GCE_INSTANCE}} --command 'sudo docker-compose restart'
      - name: Execute scenario as daemons
        uses: actions-hub/gcloud@master
        with: 
          args: compute ssh --zone ${{ secrets.GCE_INSTANCE_ZONE }} ${{secrets.GCE_INSTANCE}} --command 'sudo docker-compose up -d'
