name: Update Pathfinder data storage SSH

on:
  workflow_dispatch:


jobs:
  gcloud:
    runs-on: ubuntu-latest
    name: Restart data sstorage services on GCloud
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          GIT_CRYPT_KEY_B64: ${{secrets.GIT_CRYPT_KEY_B64}}
        with:
          host: ${{secrets.DATA_STORAGE_PUBLIC_IP}}
          user: "root"
          key: ${{secrets.GCLOUD_TEST_DATA_STORAGE_SSH_ID_RSA_PRIVATE}}
          connect_timeout: 10s
          script: |
            sudo rm -rf "pathfinder-core"
            sudo git clone "https://github.com/Pathfinder-Systems/pathfinder-core.git"
            sudo apt-get update -y
            sudo apt-get install -y "git-crypt"
            sudo apt-get install -y "cl-base64"
            sudo echo "$GIT_CRYPT_KEY_B64" > "pathfinder-core/key_base64.txt"
            sudo base64 -d "pathfinder-core/key_base64.txt" > "pathfinder-core/key"
            cd "pathfinder-core" && sudo git-crypt unlock "key"
            cd ../ && sudo rm -f "docker-compose.yaml"
            sudo mv "pathfinder-core/docker-compose/pathfinder-data-storage-start-dev.yaml" "docker-compose.yaml"
            sudo rm -rf "pathfinder-core"
            sudo docker-compose stop
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose build
            sudo docker-compose up -d

