name: Release pathfinder-core

on:
  release:
    types: [created]
    
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    name: Build and deploy docker image to DockerHb
    steps:
    - uses: actions/checkout@v2
    - name: Setup git-crypt
      run: sudo apt-get install -y git-crypt
    - name: Check git-crypt version
      run: git-crypt --version
    - name: Setup base64 util
      run: sudo apt-get install -y cl-base64
    - name: Save base64 key from GitHub secrets to file
      run: sudo echo "${{secrets.GIT_CRYPT_KEY_B64}}" > key_base64.txt
    - name: Create git-crypt key file from base64 encoded key
      run: sudo base64 -d key_base64.txt > key
    - name: Unlock secrets
      run: git-crypt unlock key
    - name: Docker Login
      uses: docker/login-action@v1.4.1
      with:
        username: danilandreev
        password: ${{secrets.DOCKER_HUB_DA_TOKEN}}
        logout: true
    - name: Echo docker version
      run: docker --version
    - name: Echo docker-compose version
      run: docker-compose --version
    - name: Build the Docker image
      run: docker-compose build
  
    - name: Tag image "pathfinder-core" as "danilandreev/pathfinder-core"
      run: docker tag pathfinder-core danilandreev/pathfinder-core
    - name: List of images in local docker registry
      run: docker images
    - name: Push image to docker
      run: docker push danilandreev/pathfinder-core
      
  github: 
    runs-on: ubuntu-latest
    name: Publish image to github packages registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup git-crypt
        run: sudo apt-get install -y git-crypt
      - name: Check git-crypt version
        run: git-crypt --version
      - name: Setup base64 util
        run: sudo apt-get install -y cl-base64
      - name: Save base64 key from GitHub secrets to file
        run: sudo echo "${{secrets.GIT_CRYPT_KEY_B64}}" > key_base64.txt
      - name: Create git-crypt key file from base64 encoded key
        run: sudo base64 -d key_base64.txt > key
      - name: Unlock secrets
        run: git-crypt unlock key
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: pathfinder-systems/pathfinder-core/pathfinder-core
          tag_with_ref: true
